import {staticFile} from 'remotion';
import ledgerJson from './ledger.json';

/**
 * The asset ledger is generated by scripts/build_ledger.py and is the auditable
 * record behind the compulsory-coverage requirement.
 *
 * 34 raw media files in the repository
 *   -> 2 logo files, excluded from reel content as overlays (prompt 4a) and
 *      exempt from coverage
 *   -> 32 coverage-relevant filenames
 *   -> 2 byte-identical duplicate pairs merged
 *        MOTU M4 (3).jpg  == MOTU M2 (10).jpg   (podcast room)
 *        MOTU M6 (11).jpg == MOTU M4 (8).jpg    (included software)
 *   == 30 DISTINCT assets, split 9 (Part 1) / 21 (Part 2).
 *
 * Covering a merged entry covers every filename in it — the files are the same
 * pixels, so there is nothing further to show.
 *
 * `part: 0` marks the two excluded logos; they carry no slug, are never copied
 * into public/img, and `A()` throws if a scene asks for one. That makes the
 * "no added logo overlay" rule structurally enforced rather than a convention.
 * It has no bearing on brand marks already printed on hardware inside a
 * supplied photograph — those are part of the photograph and are used as-is.
 */
export type LedgerEntry = {
  id: number;
  slug: string | null;
  part: number;
  product: 'M2' | 'M4' | 'M6' | 'shared' | 'brand';
  role: 'panel' | 'product' | 'macro' | 'context' | 'software' | 'logo';
  source: string;
  merged: string[];
  nRaw: number;
  kind: 'image' | 'logo';
  /** True pixel dimensions of the file in public/img. */
  w: number;
  h: number;
  alpha: boolean;
};

export const LEDGER = ledgerJson as LedgerEntry[];

const BY_ID = new Map<number, LedgerEntry>(LEDGER.map((e) => [e.id, e]));

/** Asset id -> static URL. Throws on a logo or an unknown id. */
export const A = (id: number): string => {
  const e = BY_ID.get(id);
  if (!e) throw new Error(`asset ${id} is not in the ledger`);
  if (!e.slug) {
    throw new Error(
      `asset ${id} is an excluded logo file and must not be placed in a reel`,
    );
  }
  return staticFile(`img/${e.slug}`);
};

export const meta = (id: number): LedgerEntry => {
  const e = BY_ID.get(id);
  if (!e) throw new Error(`asset ${id} is not in the ledger`);
  return e;
};

/** Natural aspect ratio (w / h) of an asset. */
export const ratio = (id: number): number => {
  const e = meta(id);
  return e.w / e.h;
};

export type Box = {x: number; y: number; w: number; h: number};

/**
 * The no-crop box solver.
 *
 * Returns the largest box with the asset's EXACT aspect ratio that fits inside
 * `maxW` x `maxH`, centred horizontally by default. Because the box matches the
 * image's own ratio, an `objectFit: contain` image fills it precisely — no
 * letterbox bars, and critically no cropping: the entire photograph is visible,
 * which is exactly what the delivery note asks for.
 *
 * `align` shifts the result inside the available width when the box is
 * narrower than `maxW`.
 */
export const fitBox = (
  id: number,
  x: number,
  y: number,
  maxW: number,
  maxH: number,
  align: 'center' | 'left' | 'right' = 'center',
): Box => {
  const r = ratio(id);
  let w = maxW;
  let h = w / r;
  if (h > maxH) {
    h = maxH;
    w = h * r;
  }
  const dx = align === 'center' ? (maxW - w) / 2 : align === 'right' ? maxW - w : 0;
  return {x: x + dx, y, w: Math.round(w), h: Math.round(h)};
};

/** Same as fitBox but also vertically centres inside maxH. */
export const fitBoxC = (
  id: number,
  x: number,
  y: number,
  maxW: number,
  maxH: number,
): Box => {
  const b = fitBox(id, x, y, maxW, maxH);
  return {...b, y: y + Math.round((maxH - b.h) / 2)};
};

export const idsForPart = (part: number): number[] =>
  LEDGER.filter((e) => e.part === part).map((e) => e.id);

export const idsForProduct = (p: LedgerEntry['product']): number[] =>
  LEDGER.filter((e) => e.product === p && e.slug).map((e) => e.id);
