// Section 10 checkpoint 8 — branding cadence, as an actual timestamped list.
//
// Confirms: Shivansh recurs at a steady interval with no gap over the AVB
// long-form guideline (<=24s), MOTU recurs noticeably less often, the website
// is the most-repeated single element, and the three MOPs and the
// best-price direction appear together near the end.
import { loadSchedule, tc } from "./_load.mjs";
import { writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const { BEATS, BEAT_STARTS, VIDEO, BRAND, PRICE, frames } = await loadSchedule();

const GAP_GUIDELINE = 24; // seconds — the AVB long-form's own longest gap

const FORM = {
  cornerLogo: "corner logo + URL",
  lowerThird: "lower-third logo + URL + region",
  brandBeat: "full branding beat (logo + role + region + URL)",
  price: "price lockup (three MOPs + best-price direction + URL)",
  contact: "contact panel (logo + URL + socials + WhatsApp + address)",
  outro: "outro lockup (both logos + three MOPs + URL + designation)",
};

const shiv = [];
const motu = [];
BEATS.forEach((b, i) => {
  const inF = BEAT_STARTS[i];
  const outF = inF + frames(b.sec);
  if (b.brand !== "none") shiv.push({ inF, outF, b, form: FORM[b.brand] ?? b.brand });
  // MOTU appears via the corner mark, and inside the outro lockup.
  if (b.motu || b.brand === "outro") motu.push({ inF, outF, b });
});

// The URL is on screen in every Shivansh form except the bare `none`.
const urlCount = shiv.length;

let fail = 0;
const bad = (m) => {
  console.log(`  FAIL ${m}`);
  fail++;
};

// Longest gap between consecutive Shivansh appearances.
let longest = 0;
let longestAt = "";
let prevOut = 0;
for (const s of shiv) {
  const gap = (s.inF - prevOut) / VIDEO.fps;
  if (gap > longest) {
    longest = gap;
    longestAt = `${tc(prevOut)} -> ${tc(s.inF)}`;
  }
  prevOut = Math.max(prevOut, s.outF);
}
const tailGap = (VIDEO.durationInFrames - prevOut) / VIDEO.fps;
if (tailGap > longest) {
  longest = tailGap;
  longestAt = `${tc(prevOut)} -> end`;
}

const lines = [];
lines.push("# Branding cadence — MOTU M-Series long-form (298 s, 1920x1080)\n");
lines.push("Generated by `npm run branding` from the same schedule that renders the video.\n");
lines.push(
  "Every logo appearance renders through the `Logo` component, which draws the supplied file\n" +
    "**exactly as given — opaque, with its own white background intact, never alpha-keyed — directly\n" +
    "on the video with no box, card or plate**. The page palette is held in a near-white range\n" +
    "(`COLORS.paper` #F6F8FA) so that white ground reads as continuous with it. The full-frame\n" +
    "branding beats additionally use a flat page so nothing shows an edge behind the artwork.\n"
);
lines.push(
  `All text and logos sit inside the Section 2.1 edge padding (56 x 52 px, pulled from the AVB\n` +
    `long-form build), so nothing critical can clip under downstream cropping or re-encode.\n`
);

lines.push(`\n## Shivansh Electronics — ${shiv.length} appearances (longest gap ${longest.toFixed(0)}s, guideline <=${GAP_GUIDELINE}s)\n`);
lines.push("| In | Out | Ch | Beat | Form |");
lines.push("|---|---|---|---|---|");
for (const s of shiv) lines.push(`| ${tc(s.inF)} | ${tc(s.outF)} | ${s.b.ch} | \`${s.b.id}\` | ${s.form} |`);

lines.push(`\n## MOTU — ${motu.length} appearances\n`);
lines.push("| In | Out | Ch | Beat |");
lines.push("|---|---|---|---|");
for (const m of motu) lines.push(`| ${tc(m.inF)} | ${tc(m.outF)} | ${m.b.ch} | \`${m.b.id}\` |`);

lines.push("\n## Checks\n");
lines.push(`- \`${BRAND.website}\` on screen in **${urlCount}** beats — more than any other single element.`);
lines.push(`- Shivansh : MOTU ratio is **${shiv.length} : ${motu.length}** — MOTU is used noticeably less often, as Section 6 requires.`);
lines.push(`- Longest Shivansh gap: **${longest.toFixed(1)}s** (${longestAt}).`);
lines.push(`- Price beat \`c7-price\` states **${PRICE.m2} / ${PRICE.m4} / ${PRICE.m6}** distinctly, plus "${PRICE.bestPrice}".`);
lines.push(`- The outro repeats all three MOPs, the URL, and the full distributor designation.`);

writeFileSync(resolve(dirname(fileURLToPath(import.meta.url)), "../BRANDING_CADENCE.md"), lines.join("\n") + "\n");

console.log(`\nSHIVANSH: ${shiv.length} appearances · longest gap ${longest.toFixed(1)}s (${longestAt})`);
console.log(`MOTU:     ${motu.length} appearances · ratio ${(shiv.length / motu.length).toFixed(1)}:1`);
console.log(`URL:      ${urlCount} beats carry ${BRAND.website}`);

if (longest > GAP_GUIDELINE) bad(`longest Shivansh gap ${longest.toFixed(1)}s exceeds the ${GAP_GUIDELINE}s guideline`);
if (motu.length >= shiv.length * 0.7) bad(`MOTU (${motu.length}) is not noticeably less frequent than Shivansh (${shiv.length})`);
const priceBeat = BEATS.find((b) => b.brand === "price");
if (!priceBeat) bad("no price lockup beat");
const outroBeat = BEATS.find((b) => b.brand === "outro");
if (!outroBeat) bad("no outro lockup beat");

console.log(fail === 0 ? "BRANDING: PASS\n" : `BRANDING: ${fail} FAILURE(S)\n`);
process.exit(fail === 0 ? 0 : 1);
