// GENERATED by scripts/prep_assets.py — do not edit by hand.
// Every size and every bounding box here was measured off the file on disk.

import type { Asset, Clip } from "./assets.ts";

export const ASSETS: Asset[] = [
 {
  "slug": "m2-01",
  "file": "img/m2-01.webp",
  "kind": "photo",
  "model": 2,
  "w": 2880,
  "h": 1396,
  "ar": 2.063,
  "bbox": [
   0.0,
   0.0,
   1.0,
   1.0
  ],
  "transparent": false
 },
 {
  "slug": "m2-03",
  "file": "img/m2-03.webp",
  "kind": "photo",
  "model": 2,
  "w": 1442,
  "h": 873,
  "ar": 1.6518,
  "bbox": [
   0.0,
   0.0,
   1.0,
   1.0
  ],
  "transparent": false
 },
 {
  "slug": "m2-04",
  "file": "img/m2-04.webp",
  "kind": "photo",
  "model": 2,
  "w": 1442,
  "h": 873,
  "ar": 1.6518,
  "bbox": [
   0.0,
   0.0,
   1.0,
   1.0
  ],
  "transparent": false
 },
 {
  "slug": "m2-05",
  "file": "img/m2-05.webp",
  "kind": "photo",
  "model": 2,
  "w": 1000,
  "h": 873,
  "ar": 1.1455,
  "bbox": [
   0.0,
   0.0,
   1.0,
   1.0
  ],
  "transparent": false
 },
 {
  "slug": "m2-06",
  "file": "img/m2-06.webp",
  "kind": "photo",
  "model": 2,
  "w": 2880,
  "h": 1516,
  "ar": 1.8997,
  "bbox": [
   0.0,
   0.0,
   1.0,
   1.0
  ],
  "transparent": false
 },
 {
  "slug": "m2-08",
  "file": "img/m2-08.webp",
  "kind": "hero",
  "model": 2,
  "w": 1879,
  "h": 948,
  "ar": 2.4244,
  "bbox": [
   0.0266,
   0.0802,
   0.9814,
   0.8608
  ],
  "transparent": false
 },
 {
  "slug": "m2-10",
  "file": "img/m2-10.webp",
  "kind": "photo",
  "model": 2,
  "w": 1442,
  "h": 873,
  "ar": 1.6518,
  "bbox": [
   0.0,
   0.0,
   1.0,
   1.0
  ],
  "transparent": false
 },
 {
  "slug": "m2-3q",
  "file": "img/m2-3q.png",
  "kind": "hero",
  "model": 2,
  "w": 1732,
  "h": 590,
  "ar": 2.9356,
  "bbox": [
   0.0,
   0.0,
   1.0,
   1.0
  ],
  "transparent": true
 },
 {
  "slug": "m2-front",
  "file": "img/m2-front.png",
  "kind": "panel",
  "model": 2,
  "w": 1212,
  "h": 301,
  "ar": 4.0754,
  "bbox": [
   0.1205,
   0.1296,
   0.8804,
   0.8804
  ],
  "transparent": true
 },
 {
  "slug": "m2-rear",
  "file": "img/m2-rear.png",
  "kind": "panel",
  "model": 2,
  "w": 2013,
  "h": 500,
  "ar": 3.6464,
  "bbox": [
   0.1192,
   0.122,
   0.8818,
   0.964
  ],
  "transparent": true
 },
 {
  "slug": "m4-01",
  "file": "img/m4-01.webp",
  "kind": "photo",
  "model": 4,
  "w": 1442,
  "h": 873,
  "ar": 1.6518,
  "bbox": [
   0.0,
   0.0,
   1.0,
   1.0
  ],
  "transparent": false
 },
 {
  "slug": "m4-02",
  "file": "img/m4-02.webp",
  "kind": "photo",
  "model": 4,
  "w": 1442,
  "h": 873,
  "ar": 1.6518,
  "bbox": [
   0.0,
   0.0,
   1.0,
   1.0
  ],
  "transparent": false
 },
 {
  "slug": "m4-03",
  "file": "img/m4-03.webp",
  "kind": "photo",
  "model": 4,
  "w": 1442,
  "h": 873,
  "ar": 1.6518,
  "bbox": [
   0.0,
   0.0,
   1.0,
   1.0
  ],
  "transparent": false
 },
 {
  "slug": "m4-04",
  "file": "img/m4-04.webp",
  "kind": "hero",
  "model": 4,
  "w": 2102,
  "h": 1061,
  "ar": 3.0048,
  "bbox": [
   0.029,
   0.099,
   0.961,
   0.7135
  ],
  "transparent": false
 },
 {
  "slug": "m4-05",
  "file": "img/m4-05.webp",
  "kind": "photo",
  "model": 4,
  "w": 2880,
  "h": 1396,
  "ar": 2.063,
  "bbox": [
   0.0,
   0.0,
   1.0,
   1.0
  ],
  "transparent": false
 },
 {
  "slug": "m4-06",
  "file": "img/m4-06.webp",
  "kind": "photo",
  "model": 4,
  "w": 1000,
  "h": 873,
  "ar": 1.1455,
  "bbox": [
   0.0,
   0.0,
   1.0,
   1.0
  ],
  "transparent": false
 },
 {
  "slug": "m4-07",
  "file": "img/m4-07.webp",
  "kind": "photo",
  "model": 4,
  "w": 2880,
  "h": 1516,
  "ar": 1.8997,
  "bbox": [
   0.0,
   0.0,
   1.0,
   1.0
  ],
  "transparent": false
 },
 {
  "slug": "m4-3q",
  "file": "img/m4-3q.png",
  "kind": "hero",
  "model": 4,
  "w": 1916,
  "h": 588,
  "ar": 3.2585,
  "bbox": [
   0.0,
   0.0,
   1.0,
   1.0
  ],
  "transparent": true
 },
 {
  "slug": "m4-front",
  "file": "img/m4-front.png",
  "kind": "panel",
  "model": 4,
  "w": 1212,
  "h": 301,
  "ar": 4.8006,
  "bbox": [
   0.014,
   0.0598,
   0.9884,
   0.8771
  ],
  "transparent": true
 },
 {
  "slug": "m4-rear",
  "file": "img/m4-rear.png",
  "kind": "panel",
  "model": 4,
  "w": 1212,
  "h": 301,
  "ar": 4.7966,
  "bbox": [
   0.014,
   0.0598,
   0.9876,
   0.8771
  ],
  "transparent": true
 },
 {
  "slug": "m6-02",
  "file": "img/m6-02.webp",
  "kind": "photo",
  "model": 6,
  "w": 2777,
  "h": 1947,
  "ar": 1.4263,
  "bbox": [
   0.0,
   0.0,
   1.0,
   1.0
  ],
  "transparent": false
 },
 {
  "slug": "m6-03",
  "file": "img/m6-03.webp",
  "kind": "photo",
  "model": 6,
  "w": 3000,
  "h": 2000,
  "ar": 1.5,
  "bbox": [
   0.0,
   0.0,
   1.0,
   1.0
  ],
  "transparent": false
 },
 {
  "slug": "m6-04",
  "file": "img/m6-04.webp",
  "kind": "photo",
  "model": 6,
  "w": 2830,
  "h": 2737,
  "ar": 1.034,
  "bbox": [
   0.0,
   0.0,
   1.0,
   1.0
  ],
  "transparent": false
 },
 {
  "slug": "m6-05",
  "file": "img/m6-05.webp",
  "kind": "photo",
  "model": 6,
  "w": 3000,
  "h": 2223,
  "ar": 1.3495,
  "bbox": [
   0.0,
   0.0,
   1.0,
   1.0
  ],
  "transparent": false
 },
 {
  "slug": "m6-06",
  "file": "img/m6-06.webp",
  "kind": "photo",
  "model": 6,
  "w": 2821,
  "h": 1529,
  "ar": 1.845,
  "bbox": [
   0.0,
   0.0,
   1.0,
   1.0
  ],
  "transparent": false
 },
 {
  "slug": "m6-07",
  "file": "img/m6-07.webp",
  "kind": "photo",
  "model": 6,
  "w": 3000,
  "h": 1740,
  "ar": 1.7241,
  "bbox": [
   0.0,
   0.0,
   1.0,
   1.0
  ],
  "transparent": false
 },
 {
  "slug": "m6-08",
  "file": "img/m6-08.webp",
  "kind": "photo",
  "model": 6,
  "w": 3000,
  "h": 2101,
  "ar": 1.4279,
  "bbox": [
   0.0,
   0.0,
   1.0,
   1.0
  ],
  "transparent": false
 },
 {
  "slug": "m6-09",
  "file": "img/m6-09.webp",
  "kind": "photo",
  "model": 6,
  "w": 2830,
  "h": 2737,
  "ar": 1.034,
  "bbox": [
   0.0,
   0.0,
   1.0,
   1.0
  ],
  "transparent": false
 },
 {
  "slug": "m6-10",
  "file": "img/m6-10.webp",
  "kind": "photo",
  "model": 6,
  "w": 3000,
  "h": 2085,
  "ar": 1.4388,
  "bbox": [
   0.0,
   0.0,
   1.0,
   1.0
  ],
  "transparent": false
 },
 {
  "slug": "m6-front",
  "file": "img/m6-front.png",
  "kind": "panel",
  "model": 6,
  "w": 2442,
  "h": 749,
  "ar": 3.6337,
  "bbox": [
   0.0233,
   0.0721,
   0.9771,
   0.9279
  ],
  "transparent": true
 },
 {
  "slug": "m6-meter",
  "file": "img/m6-meter.webp",
  "kind": "panel",
  "model": 6,
  "w": 911,
  "h": 591,
  "ar": 1.5415,
  "bbox": [
   0.0,
   0.0,
   1.0,
   1.0
  ],
  "transparent": false
 },
 {
  "slug": "m6-rear",
  "file": "img/m6-rear.png",
  "kind": "panel",
  "model": 6,
  "w": 3530,
  "h": 800,
  "ar": 5.091,
  "bbox": [
   0.0278,
   0.0912,
   0.9725,
   0.91
  ],
  "transparent": true
 },
 {
  "slug": "motu-logo",
  "file": "img/motu-logo.png",
  "kind": "logo",
  "model": 0,
  "w": 2372,
  "h": 714,
  "ar": 6.1949,
  "bbox": [
   0.0299,
   0.2353,
   0.9701,
   0.7395
  ],
  "transparent": true
 },
 {
  "slug": "shivansh-logo",
  "file": "img/shivansh-logo.png",
  "kind": "logo",
  "model": 0,
  "w": 2372,
  "h": 714,
  "ar": 3.3221,
  "bbox": [
   0.0,
   0.0,
   1.0,
   1.0
  ],
  "transparent": true
 }
];

export const CLIPS: Clip[] = [
 {
  "slug": "broll-01-home-studio",
  "file": "broll/broll-01-home-studio.mp4",
  "w": 1928,
  "h": 1076,
  "ar": 1.7918,
  "dur": 5.04
 },
 {
  "slug": "broll-02-podcast-table",
  "file": "broll/broll-02-podcast-table.mp4",
  "w": 1928,
  "h": 1076,
  "ar": 1.7918,
  "dur": 5.04
 },
 {
  "slug": "broll-03-teaching-lab",
  "file": "broll/broll-03-teaching-lab.mp4",
  "w": 1928,
  "h": 1076,
  "ar": 1.7918,
  "dur": 5.04
 },
 {
  "slug": "broll-04-rehearsal",
  "file": "broll/broll-04-rehearsal.mp4",
  "w": 1928,
  "h": 1076,
  "ar": 1.7918,
  "dur": 5.04
 },
 {
  "slug": "broll-05-location-kit",
  "file": "broll/broll-05-location-kit.mp4",
  "w": 1928,
  "h": 1076,
  "ar": 1.7918,
  "dur": 5.04
 },
 {
  "slug": "broll-06-streaming-desk",
  "file": "broll/broll-06-streaming-desk.mp4",
  "w": 1928,
  "h": 1076,
  "ar": 1.7918,
  "dur": 5.04
 },
 {
  "slug": "broll-07-dealer-counter",
  "file": "broll/broll-07-dealer-counter.mp4",
  "w": 1928,
  "h": 1076,
  "ar": 1.7918,
  "dur": 5.04
 },
 {
  "slug": "broll-08-listening-room",
  "file": "broll/broll-08-listening-room.mp4",
  "w": 1928,
  "h": 1076,
  "ar": 1.7918,
  "dur": 5.04
 },
 {
  "slug": "broll-09-live-event",
  "file": "broll/broll-09-live-event.mp4",
  "w": 1928,
  "h": 1076,
  "ar": 1.7918,
  "dur": 5.04
 },
 {
  "slug": "broll-10-producers",
  "file": "broll/broll-10-producers.mp4",
  "w": 1928,
  "h": 1076,
  "ar": 1.7918,
  "dur": 5.04
 }
];

export const REGION_LUM: Record<string, number> = {
 "m2.inputs": 0.1711,
 "m2.meter": 0.2783,
 "m2.monitor": 0.2363,
 "m2.phones": 0.1259,
 "m2.usbc": 0.2229,
 "m2.midi": 0.201,
 "m4.inputs": 0.2167,
 "m4.mix": 0.2563,
 "m4.meter": 0.3146,
 "m4.monitor": 0.2494,
 "m4.rearline": 0.2448,
 "m6.gains": 0.2343,
 "m6.mix": 0.2621,
 "m6.meter": 0.274,
 "m6.monitor": 0.2773,
 "m6.phones": 0.2454,
 "m6.rearmic": 0.2206,
 "m6.power": 0.2093
};
