// Section 10 checkpoint 7 — curated-image completeness.
//
// Every image in the curated selection must appear in at least one beat, and
// must be shown FULLY and UNCROPPED at some point in its treatment. Every
// treatment in this build renders through Plate (`object-fit: contain`), so
// "appears" and "appears complete" are the same statement — the check that
// matters is that nothing selected is orphaned, and that no beat references an
// image that is not in the selection.
import { loadSchedule } from "./_load.mjs";
import { tc } from "./_load.mjs";
import { writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const { BEATS, BEAT_STARTS, ASSETS, frames } = await loadSchedule();

const used = new Map(); // idx -> [{beat, in, out, treatment}]
BEATS.forEach((b, i) => {
  b.images.forEach((idx) => {
    if (!used.has(idx)) used.set(idx, []);
    used.get(idx).push({
      beat: b.id,
      ch: b.ch,
      inF: BEAT_STARTS[i],
      outF: BEAT_STARTS[i] + frames(b.sec),
      kind: b.kind,
    });
  });
});

let fail = 0;
const lines = [];
lines.push("# Curated-image coverage — MOTU M-Series portrait short (178 s)\n");
lines.push("Generated by `npm run coverage` from the same schedule that renders the video.\n");
lines.push(
  "Every treatment renders through `Plate`, which is `object-fit: contain`. No image is ever\n" +
    "cropped, clipped or trimmed to fit the runtime — where an aspect ratio does not match its\n" +
    "slot the difference is absorbed by the ground treatment, never by cutting into the subject.\n"
);
lines.push("| # | Asset | Product | Appearances | First in | Treatment(s) |");
lines.push("|---|---|---|---|---|---|");

ASSETS.forEach((a, idx) => {
  const u = used.get(idx) ?? [];
  if (u.length === 0) {
    console.log(`  FAIL ${a.key} (${a.file}) is selected but never placed`);
    fail++;
    return;
  }
  const kinds = [...new Set(u.map((x) => x.kind))].join(", ");
  lines.push(
    `| ${idx} | \`${a.key}\` — ${a.file} | ${a.product} | ${u.length} | ${tc(u[0].inF)} | ${kinds} |`
  );
});

// Nothing referenced that is not in the selection.
for (const [idx] of used) {
  if (!ASSETS[idx]) {
    console.log(`  FAIL beat references asset index ${idx}, which is not in the selection`);
    fail++;
  }
}

const perProduct = {};
ASSETS.forEach((a) => (perProduct[a.product] = (perProduct[a.product] ?? 0) + 1));

lines.push("\n## Selection per product\n");
lines.push("| Product | Selected |");
lines.push("|---|---|");
for (const [p, n] of Object.entries(perProduct)) lines.push(`| ${p} | ${n} |`);

lines.push("\n## Deliberately excluded\n");
lines.push("| File | Reason |");
lines.push("|---|---|");
lines.push("| `MOTU M2 (5).jpg`, `MOTU M4 (1).jpg`, `MOTU M6 (6).jpg` | Cut from the project selection entirely — see the landscape build's coverage report. |");
lines.push("| `m2Couch`, `m2Glass`, `m2Dark`, `m4Desk`, `m4Drums`, `m4Cable`, `m6Dark`, `m6Low`, `m6Bright`, `m6Studio` | Wide landscape room shots (aspect 1.7-2.9). At 1080px wide these either letterbox to a sliver with the product unreadable, or would have to be cropped — and Section 3 does not allow cropping. Cut from the selection instead, which is the response Section 3 asks for. They ARE used in the landscape deliverable. |");
lines.push("\n## Byte-identical duplicates, reclassified rather than double-counted\n");
lines.push("| Pair | Resolution |");
lines.push("|---|---|");
lines.push("| `MOTU M4 (8).jpg` = `MOTU M6 (11).jpg` | Not a product shot — the software-bundle montage. Kept once as shared `shSoftware`. |");
lines.push("| `MOTU M2 (10).jpg` = `MOTU M4 (3).jpg` | Wide podcast room, unit unattributable. Kept once as shared `shRoom`. |");

const out = resolve(dirname(fileURLToPath(import.meta.url)), "../ASSET_COVERAGE.md");
writeFileSync(out, lines.join("\n") + "\n");

console.log(`\nCOVERAGE: ${ASSETS.length} selected images, ${used.size} placed`);
console.log(`  per product: ${Object.entries(perProduct).map(([p, n]) => `${p}=${n}`).join("  ")}`);
console.log(fail === 0 ? "COVERAGE: PASS — every selected image appears complete and uncropped.\n" : `COVERAGE: ${fail} FAILURE(S)\n`);
process.exit(fail === 0 ? 0 : 1);
