// Section 10 checkpoint 7 — curated-image completeness.
//
// Every image in the curated selection must appear in at least one beat, and
// must be shown FULLY and UNCROPPED at some point in its treatment. Every
// treatment in this build renders through Plate (`object-fit: contain`), so
// "appears" and "appears complete" are the same statement — the check that
// matters is that nothing selected is orphaned, and that no beat references an
// image that is not in the selection.
import { loadSchedule } from "./_load.mjs";
import { tc } from "./_load.mjs";
import { writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const { BEATS, BEAT_STARTS, ASSETS, frames } = await loadSchedule();

const used = new Map(); // idx -> [{beat, in, out, treatment}]
BEATS.forEach((b, i) => {
  b.images.forEach((idx) => {
    if (!used.has(idx)) used.set(idx, []);
    used.get(idx).push({
      beat: b.id,
      ch: b.ch,
      inF: BEAT_STARTS[i],
      outF: BEAT_STARTS[i] + frames(b.sec),
      kind: b.kind,
    });
  });
});

let fail = 0;
const lines = [];
lines.push("# Image coverage — MOTU M-Series portrait reel (178 s) — FULL 30-IMAGE BUILD\n");
lines.push("Generated by `npm run coverage` from the same schedule that renders the video.\n");
lines.push(
  "Every treatment renders through `Plate`, which is `object-fit: contain`. No image is ever\n" +
    "cropped, clipped or trimmed to fit the runtime — where an aspect ratio does not match its\n" +
    "slot the difference is absorbed by the ground treatment, never by cutting into the subject.\n"
);
lines.push("| # | Asset | Product | Appearances | First in | Treatment(s) |");
lines.push("|---|---|---|---|---|---|");

ASSETS.forEach((a, idx) => {
  const u = used.get(idx) ?? [];
  if (u.length === 0) {
    console.log(`  FAIL ${a.key} (${a.file}) is selected but never placed`);
    fail++;
    return;
  }
  const kinds = [...new Set(u.map((x) => x.kind))].join(", ");
  lines.push(
    `| ${idx} | \`${a.key}\` — ${a.file} | ${a.product} | ${u.length} | ${tc(u[0].inF)} | ${kinds} |`
  );
});

// Nothing referenced that is not in the selection.
for (const [idx] of used) {
  if (!ASSETS[idx]) {
    console.log(`  FAIL beat references asset index ${idx}, which is not in the selection`);
    fail++;
  }
}

const perProduct = {};
ASSETS.forEach((a) => (perProduct[a.product] = (perProduct[a.product] ?? 0) + 1));

lines.push("\n## Selection per product\n");
lines.push("| Product | Selected |");
lines.push("|---|---|");
for (const [p, n] of Object.entries(perProduct)) lines.push(`| ${p} | ${n} |`);

lines.push("\n## Target set — fixed and named, not curated\n");
lines.push("This reel carries **all 30 unique images**: the 27 the 298 s landscape video used (read from");
lines.push("that build's own committed `ASSET_COVERAGE.md`), plus the 3 that both prior builds had");
lines.push("excluded, reinstated by direct instruction. Nothing is excluded on a curation judgment.\n");
lines.push("| Reinstated | Appears alongside (not instead of) |");
lines.push("|---|---|");
lines.push("| `m2Alt` — MOTU M2 (5).jpg | `m2Glass` — MOTU M2 (3).jpg |");
lines.push("| `m4Alt` — MOTU M4 (1).jpg | `m4Desk` — MOTU M4 (7).jpg |");
lines.push("| `m6Alt` — MOTU M6 (6).jpg | `m6Bright` — MOTU M6 (8).jpg |");
lines.push("\n## Wide-aspect treatment — FIT + FILL, never cropped\n");
lines.push("19 of the 30 are landscape-oriented (AR 1.40-3.45). Each is scaled **complete** to the frame");
lines.push("width and the remaining height filled with a blurred, dimmed copy of the same image — a");
lines.push("colour field pulled from its own palette. The complete image is always the subject; nothing");
lines.push("is cropped to fit, and nothing is dropped for being the wrong shape.\n");
lines.push("| fit | count | images |");
lines.push("|---|---|---|");
for (const f of ["plate", "fill", "native"]) {
  const g = ASSETS.filter((a) => a.fit === f);
  lines.push(`| \`${f}\` | ${g.length} | ${g.map((a) => a.key).join(", ")} |`);
}
lines.push("\n## Byte-identical duplicates, collapsed rather than double-counted\n");
lines.push("| Pair | Resolution |");
lines.push("|---|---|");
lines.push("| `MOTU M4 (8).jpg` = `MOTU M6 (11).jpg` | Not a product shot — the software-bundle montage. Kept once as `shSoftware`. |");
lines.push("| `MOTU M2 (10).jpg` = `MOTU M4 (3).jpg` | Wide podcast room, unit unattributable. Kept once as `shRoom`. |");
lines.push("\n32 raw files - 2 collapsed duplicates = **30 unique = the target**.\n");

const out = resolve(dirname(fileURLToPath(import.meta.url)), "../ASSET_COVERAGE.md");
writeFileSync(out, lines.join("\n") + "\n");

console.log(`\nCOVERAGE: ${ASSETS.length} selected images, ${used.size} placed`);
console.log(`  per product: ${Object.entries(perProduct).map(([p, n]) => `${p}=${n}`).join("  ")}`);
console.log(fail === 0 ? "COVERAGE: PASS — every selected image appears complete and uncropped.\n" : `COVERAGE: ${fail} FAILURE(S)\n`);
process.exit(fail === 0 ? 0 : 1);
