// GENERATED by scripts/extract-hits.mjs — do not edit by hand.
// Every hit the 25 scene components fire, at absolute master frames.
// 32 hits across 24 scenes.
export type MasterHit = { scene: string; file: string; at: number; volume: number };

export const HITS: MasterHit[] = [
  {
    "scene": "hook-the-difference",
    "file": "riser.mp3",
    "at": 6,
    "volume": 0.42
  },
  {
    "scene": "the-old-trade-off",
    "file": "Impact.mp3",
    "at": 258,
    "volume": 0.5
  },
  {
    "scene": "one-engine-three-sizes",
    "file": "avb/rj45-snap.wav",
    "at": 460,
    "volume": 0.42
  },
  {
    "scene": "one-engine-three-sizes",
    "file": "avb/rj45-snap.wav",
    "at": 508,
    "volume": 0.42
  },
  {
    "scene": "one-engine-three-sizes",
    "file": "avb/rj45-snap.wav",
    "at": 556,
    "volume": 0.42
  },
  {
    "scene": "shared-converter",
    "file": "avb/avb-ping.wav",
    "at": 762,
    "volume": 0.4
  },
  {
    "scene": "shared-noise-and-latency",
    "file": "avb/data-stream.wav",
    "at": 986,
    "volume": 0.38
  },
  {
    "scene": "shared-metering",
    "file": "avb/encoder-click.wav",
    "at": 1214,
    "volume": 0.4
  },
  {
    "scene": "m2-introduction",
    "file": "Zoomin-OR-out.mp3",
    "at": 1354,
    "volume": 0.4
  },
  {
    "scene": "m2-front-panel",
    "file": "Zoomin-OR-out.mp3",
    "at": 1538,
    "volume": 0.4
  },
  {
    "scene": "m2-rear-panel",
    "file": "avb/encoder-click.wav",
    "at": 1812,
    "volume": 0.4
  },
  {
    "scene": "m2-in-the-room",
    "file": "transitions.mp3",
    "at": 2094,
    "volume": 0.34
  },
  {
    "scene": "m2-in-the-room",
    "file": "transitions.mp3",
    "at": 2184,
    "volume": 0.34
  },
  {
    "scene": "m2-price",
    "file": "avb/avb-ping.wav",
    "at": 2294,
    "volume": 0.42
  },
  {
    "scene": "m4-introduction",
    "file": "Zoomin-OR-out.mp3",
    "at": 2434,
    "volume": 0.4
  },
  {
    "scene": "m4-front-panel",
    "file": "avb/encoder-click.wav",
    "at": 2588,
    "volume": 0.4
  },
  {
    "scene": "m4-rear-panel",
    "file": "avb/encoder-click.wav",
    "at": 2862,
    "volume": 0.4
  },
  {
    "scene": "m4-in-the-room",
    "file": "transitions.mp3",
    "at": 3144,
    "volume": 0.34
  },
  {
    "scene": "m4-in-the-room",
    "file": "transitions.mp3",
    "at": 3234,
    "volume": 0.34
  },
  {
    "scene": "m4-price",
    "file": "avb/avb-ping.wav",
    "at": 3344,
    "volume": 0.42
  },
  {
    "scene": "m6-introduction",
    "file": "Zoomin-OR-out.mp3",
    "at": 3484,
    "volume": 0.4
  },
  {
    "scene": "m6-front-panel",
    "file": "avb/rj45-snap.wav",
    "at": 3638,
    "volume": 0.4
  },
  {
    "scene": "m6-rear-panel",
    "file": "avb/encoder-click.wav",
    "at": 3912,
    "volume": 0.4
  },
  {
    "scene": "m6-control-room",
    "file": "avb/talkback-click.wav",
    "at": 4132,
    "volume": 0.36
  },
  {
    "scene": "m6-control-room",
    "file": "avb/talkback-click.wav",
    "at": 4176,
    "volume": 0.36
  },
  {
    "scene": "m6-control-room",
    "file": "avb/talkback-click.wav",
    "at": 4220,
    "volume": 0.36
  },
  {
    "scene": "m6-full-ensemble",
    "file": "transitions.mp3",
    "at": 4404,
    "volume": 0.34
  },
  {
    "scene": "m6-full-ensemble",
    "file": "transitions.mp3",
    "at": 4494,
    "volume": 0.34
  },
  {
    "scene": "m6-price",
    "file": "avb/avb-ping.wav",
    "at": 4604,
    "volume": 0.42
  },
  {
    "scene": "shared-extras",
    "file": "Popups.mp3",
    "at": 4750,
    "volume": 0.4
  },
  {
    "scene": "all-three-prices-and-cta",
    "file": "avb/avb-ping.wav",
    "at": 4962,
    "volume": 0.4
  },
  {
    "scene": "all-three-prices-and-cta",
    "file": "aha-moment.MP3",
    "at": 5068,
    "volume": 0.38
  }
];
