// AUTO-GENERATED by scripts/prep-assets.mjs — do not edit by hand.
// 30 distinct images from 32 filenames in the repository root
// (2 byte-identical duplicates collapsed).
//
// kind:    panel (transparent ultra-wide plan) | cutout (transparent) | photo
// subject: hardware | panel | context | detail | bundle
//
// `covers` lists every original filename this one image satisfies, so the
// coverage ledger can prove all 32 are accounted for.

export type AssetKind = "panel" | "cutout" | "photo";
export type AssetSubject = "hardware" | "panel" | "context" | "detail" | "bundle";
export type ProductKey = "pm2" | "pm4" | "pm6" | "shared";

export type Asset = {
  slug: string;
  file: string;
  /** A 512 px copy, for the darkened wash behind a full-bleed shot. */
  bg: string;
  product: ProductKey;
  w: number;
  h: number;
  ar: number;
  kind: AssetKind;
  subject: AssetSubject;
  alpha: boolean;
  covers: string[];
};

export const ASSETS: Asset[] = [
 {
  "slug": "motu-m2-1-jpg",
  "file": "motu-m2-1-jpg.jpg",
  "bg": "bg/motu-m2-1-jpg.jpg",
  "product": "pm2",
  "w": 2880,
  "h": 1396,
  "ar": 2.063,
  "kind": "photo",
  "subject": "hardware",
  "alpha": false,
  "covers": [
   "MOTU M2 (1).jpg"
  ]
 },
 {
  "slug": "motu-m2-10-jpg",
  "file": "motu-m2-10-jpg.jpg",
  "bg": "bg/motu-m2-10-jpg.jpg",
  "product": "pm2",
  "w": 1442,
  "h": 873,
  "ar": 1.652,
  "kind": "photo",
  "subject": "context",
  "alpha": false,
  "covers": [
   "MOTU M2 (10).jpg",
   "MOTU M4 (3).jpg"
  ]
 },
 {
  "slug": "motu-m2-2-png",
  "file": "motu-m2-2-png.png",
  "bg": "bg/motu-m2-2-png.jpg",
  "product": "pm2",
  "w": 1212,
  "h": 301,
  "ar": 4.027,
  "kind": "panel",
  "subject": "panel",
  "alpha": true,
  "covers": [
   "MOTU M2 (2).png"
  ]
 },
 {
  "slug": "motu-m2-3-jpg",
  "file": "motu-m2-3-jpg.jpg",
  "bg": "bg/motu-m2-3-jpg.jpg",
  "product": "pm2",
  "w": 1442,
  "h": 873,
  "ar": 1.652,
  "kind": "photo",
  "subject": "hardware",
  "alpha": false,
  "covers": [
   "MOTU M2 (3).jpg"
  ]
 },
 {
  "slug": "motu-m2-4-jpg",
  "file": "motu-m2-4-jpg.jpg",
  "bg": "bg/motu-m2-4-jpg.jpg",
  "product": "pm2",
  "w": 1442,
  "h": 873,
  "ar": 1.652,
  "kind": "photo",
  "subject": "hardware",
  "alpha": false,
  "covers": [
   "MOTU M2 (4).jpg"
  ]
 },
 {
  "slug": "motu-m2-5-jpg",
  "file": "motu-m2-5-jpg.jpg",
  "bg": "bg/motu-m2-5-jpg.jpg",
  "product": "pm2",
  "w": 1000,
  "h": 873,
  "ar": 1.145,
  "kind": "photo",
  "subject": "hardware",
  "alpha": false,
  "covers": [
   "MOTU M2 (5).jpg"
  ]
 },
 {
  "slug": "motu-m2-6-jpg",
  "file": "motu-m2-6-jpg.jpg",
  "bg": "bg/motu-m2-6-jpg.jpg",
  "product": "pm2",
  "w": 2880,
  "h": 1516,
  "ar": 1.9,
  "kind": "photo",
  "subject": "context",
  "alpha": false,
  "covers": [
   "MOTU M2 (6).jpg"
  ]
 },
 {
  "slug": "motu-m2-8-jpg",
  "file": "motu-m2-8-jpg.jpg",
  "bg": "bg/motu-m2-8-jpg.jpg",
  "product": "pm2",
  "w": 1879,
  "h": 948,
  "ar": 1.982,
  "kind": "photo",
  "subject": "hardware",
  "alpha": false,
  "covers": [
   "MOTU M2 (8).jpg"
  ]
 },
 {
  "slug": "motu-m2-9-png",
  "file": "motu-m2-9-png.png",
  "bg": "bg/motu-m2-9-png.jpg",
  "product": "pm2",
  "w": 2013,
  "h": 500,
  "ar": 4.026,
  "kind": "panel",
  "subject": "panel",
  "alpha": true,
  "covers": [
   "MOTU M2 (9).png"
  ]
 },
 {
  "slug": "motu-m4-1-jpg",
  "file": "motu-m4-1-jpg.jpg",
  "bg": "bg/motu-m4-1-jpg.jpg",
  "product": "pm4",
  "w": 1442,
  "h": 873,
  "ar": 1.652,
  "kind": "photo",
  "subject": "hardware",
  "alpha": false,
  "covers": [
   "MOTU M4 (1).jpg"
  ]
 },
 {
  "slug": "motu-m4-1-png",
  "file": "motu-m4-1-png.png",
  "bg": "bg/motu-m4-1-png.jpg",
  "product": "pm4",
  "w": 1212,
  "h": 301,
  "ar": 4.027,
  "kind": "panel",
  "subject": "panel",
  "alpha": true,
  "covers": [
   "MOTU M4 (1).png"
  ]
 },
 {
  "slug": "motu-m4-2-jpg",
  "file": "motu-m4-2-jpg.jpg",
  "bg": "bg/motu-m4-2-jpg.jpg",
  "product": "pm4",
  "w": 1442,
  "h": 873,
  "ar": 1.652,
  "kind": "photo",
  "subject": "hardware",
  "alpha": false,
  "covers": [
   "MOTU M4 (2).jpg"
  ]
 },
 {
  "slug": "motu-m4-2-png",
  "file": "motu-m4-2-png.png",
  "bg": "bg/motu-m4-2-png.jpg",
  "product": "pm4",
  "w": 1212,
  "h": 301,
  "ar": 4.027,
  "kind": "panel",
  "subject": "panel",
  "alpha": true,
  "covers": [
   "MOTU M4 (2).png"
  ]
 },
 {
  "slug": "motu-m4-4-jpg",
  "file": "motu-m4-4-jpg.jpg",
  "bg": "bg/motu-m4-4-jpg.jpg",
  "product": "pm4",
  "w": 2102,
  "h": 1061,
  "ar": 1.981,
  "kind": "photo",
  "subject": "hardware",
  "alpha": false,
  "covers": [
   "MOTU M4 (4).jpg"
  ]
 },
 {
  "slug": "motu-m4-5-jpg",
  "file": "motu-m4-5-jpg.jpg",
  "bg": "bg/motu-m4-5-jpg.jpg",
  "product": "pm4",
  "w": 2880,
  "h": 1396,
  "ar": 2.063,
  "kind": "photo",
  "subject": "hardware",
  "alpha": false,
  "covers": [
   "MOTU M4 (5).jpg"
  ]
 },
 {
  "slug": "motu-m4-6-jpg",
  "file": "motu-m4-6-jpg.jpg",
  "bg": "bg/motu-m4-6-jpg.jpg",
  "product": "pm4",
  "w": 1000,
  "h": 873,
  "ar": 1.145,
  "kind": "photo",
  "subject": "hardware",
  "alpha": false,
  "covers": [
   "MOTU M4 (6).jpg"
  ]
 },
 {
  "slug": "motu-m4-7-jpg",
  "file": "motu-m4-7-jpg.jpg",
  "bg": "bg/motu-m4-7-jpg.jpg",
  "product": "pm4",
  "w": 2880,
  "h": 1516,
  "ar": 1.9,
  "kind": "photo",
  "subject": "hardware",
  "alpha": false,
  "covers": [
   "MOTU M4 (7).jpg"
  ]
 },
 {
  "slug": "motu-m4-8-jpg",
  "file": "motu-m4-8-jpg.jpg",
  "bg": "bg/motu-m4-8-jpg.jpg",
  "product": "pm4",
  "w": 2880,
  "h": 834,
  "ar": 3.453,
  "kind": "photo",
  "subject": "bundle",
  "alpha": false,
  "covers": [
   "MOTU M4 (8).jpg",
   "MOTU M6 (11).jpg"
  ]
 },
 {
  "slug": "motu-m6-1-jpg",
  "file": "motu-m6-1-jpg.jpg",
  "bg": "bg/motu-m6-1-jpg.jpg",
  "product": "pm6",
  "w": 911,
  "h": 591,
  "ar": 1.541,
  "kind": "photo",
  "subject": "detail",
  "alpha": false,
  "covers": [
   "MOTU M6 (1).jpg"
  ]
 },
 {
  "slug": "motu-m6-1-png",
  "file": "motu-m6-1-png.png",
  "bg": "bg/motu-m6-1-png.jpg",
  "product": "pm6",
  "w": 2442,
  "h": 749,
  "ar": 3.26,
  "kind": "panel",
  "subject": "panel",
  "alpha": true,
  "covers": [
   "MOTU M6 (1).png"
  ]
 },
 {
  "slug": "motu-m6-10-jpg",
  "file": "motu-m6-10-jpg.jpg",
  "bg": "bg/motu-m6-10-jpg.jpg",
  "product": "pm6",
  "w": 3000,
  "h": 2085,
  "ar": 1.439,
  "kind": "photo",
  "subject": "context",
  "alpha": false,
  "covers": [
   "MOTU M6 (10).jpg"
  ]
 },
 {
  "slug": "motu-m6-2-jpg",
  "file": "motu-m6-2-jpg.jpg",
  "bg": "bg/motu-m6-2-jpg.jpg",
  "product": "pm6",
  "w": 2777,
  "h": 1947,
  "ar": 1.426,
  "kind": "photo",
  "subject": "hardware",
  "alpha": false,
  "covers": [
   "MOTU M6 (2).jpg"
  ]
 },
 {
  "slug": "motu-m6-2-png",
  "file": "motu-m6-2-png.png",
  "bg": "bg/motu-m6-2-png.jpg",
  "product": "pm6",
  "w": 3000,
  "h": 680,
  "ar": 4.412,
  "kind": "panel",
  "subject": "panel",
  "alpha": true,
  "covers": [
   "MOTU M6 (2).png"
  ]
 },
 {
  "slug": "motu-m6-3-jpg",
  "file": "motu-m6-3-jpg.jpg",
  "bg": "bg/motu-m6-3-jpg.jpg",
  "product": "pm6",
  "w": 3000,
  "h": 2000,
  "ar": 1.5,
  "kind": "photo",
  "subject": "hardware",
  "alpha": false,
  "covers": [
   "MOTU M6 (3).jpg"
  ]
 },
 {
  "slug": "motu-m6-4-jpg",
  "file": "motu-m6-4-jpg.jpg",
  "bg": "bg/motu-m6-4-jpg.jpg",
  "product": "pm6",
  "w": 2830,
  "h": 2737,
  "ar": 1.034,
  "kind": "photo",
  "subject": "hardware",
  "alpha": false,
  "covers": [
   "MOTU M6 (4).jpg"
  ]
 },
 {
  "slug": "motu-m6-5-jpg",
  "file": "motu-m6-5-jpg.jpg",
  "bg": "bg/motu-m6-5-jpg.jpg",
  "product": "pm6",
  "w": 3000,
  "h": 2223,
  "ar": 1.35,
  "kind": "photo",
  "subject": "hardware",
  "alpha": false,
  "covers": [
   "MOTU M6 (5).jpg"
  ]
 },
 {
  "slug": "motu-m6-6-jpg",
  "file": "motu-m6-6-jpg.jpg",
  "bg": "bg/motu-m6-6-jpg.jpg",
  "product": "pm6",
  "w": 2821,
  "h": 1529,
  "ar": 1.845,
  "kind": "photo",
  "subject": "hardware",
  "alpha": false,
  "covers": [
   "MOTU M6 (6).jpg"
  ]
 },
 {
  "slug": "motu-m6-7-jpg",
  "file": "motu-m6-7-jpg.jpg",
  "bg": "bg/motu-m6-7-jpg.jpg",
  "product": "pm6",
  "w": 3000,
  "h": 1740,
  "ar": 1.724,
  "kind": "photo",
  "subject": "hardware",
  "alpha": false,
  "covers": [
   "MOTU M6 (7).jpg"
  ]
 },
 {
  "slug": "motu-m6-8-jpg",
  "file": "motu-m6-8-jpg.jpg",
  "bg": "bg/motu-m6-8-jpg.jpg",
  "product": "pm6",
  "w": 3000,
  "h": 2101,
  "ar": 1.428,
  "kind": "photo",
  "subject": "hardware",
  "alpha": false,
  "covers": [
   "MOTU M6 (8).jpg"
  ]
 },
 {
  "slug": "motu-m6-9-jpg",
  "file": "motu-m6-9-jpg.jpg",
  "bg": "bg/motu-m6-9-jpg.jpg",
  "product": "pm6",
  "w": 2830,
  "h": 2737,
  "ar": 1.034,
  "kind": "photo",
  "subject": "hardware",
  "alpha": false,
  "covers": [
   "MOTU M6 (9).jpg"
  ]
 }
];

export const REPO_FILE_COUNT = 32;
