/**
 * Lifts every sound-effect hit out of the 25 scene components and re-expresses
 * it at MASTER timecode, so the standalone SFX deliverable is generated from
 * the same source of truth as the hits baked into the scene renders.
 *
 *   usage: node scripts/extract-hits.mjs
 *   writes: flick-output/remotion/src/audio/hits.ts
 */
import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const remotion = join(root, "flick-output", "remotion");
const spec = JSON.parse(readFileSync(join(root, "flick-output", "scene-spec.json"), "utf8"));

const files = readdirSync(join(remotion, "src", "scenes")).filter((f) => f.endsWith(".tsx")).sort();
if (files.length !== spec.length) throw new Error(`scene count mismatch: ${files.length} vs ${spec.length}`);

const HIT = /\{\s*file:\s*"([^"]+)",\s*at:\s*(\d+)\s*(?:,\s*volume:\s*([\d.]+)\s*)?\}/g;

const hits = [];
spec.forEach((s, i) => {
  const src = readFileSync(join(remotion, "src", "scenes", files[i]), "utf8");
  for (const m of src.matchAll(HIT)) {
    const at = s.from + Number(m[2]);
    if (at >= s.from + s.durationInFrames) throw new Error(`${s.id}: hit at ${m[2]} is past the scene`);
    hits.push({ scene: s.id, file: m[1], at, volume: m[3] ? Number(m[3]) : 0.5 });
  }
});
hits.sort((a, b) => a.at - b.at);

const out = `// GENERATED by scripts/extract-hits.mjs — do not edit by hand.
// Every hit the 25 scene components fire, at absolute master frames.
// ${hits.length} hits across ${new Set(hits.map((h) => h.scene)).size} scenes.
export type MasterHit = { scene: string; file: string; at: number; volume: number };

export const HITS: MasterHit[] = ${JSON.stringify(hits, null, 2)};
`;
writeFileSync(join(remotion, "src", "audio", "hits.ts"), out);

const byFile = {};
for (const h of hits) byFile[h.file] = (byFile[h.file] ?? 0) + 1;
console.log(`${hits.length} hits written to src/audio/hits.ts`);
for (const [f, n] of Object.entries(byFile).sort((a, b) => b[1] - a[1])) {
  console.log(`  ${String(n).padStart(2)} x ${f}${f.startsWith("avb/") ? "   (AVB-sourced)" : "   (Flick's own)"}`);
}
