#!/usr/bin/env node
// Generates ASSET_COVERAGE_MSERIES_REEL_90S.md — the coverage proof for the
// instruction that every M2, M4 and M6 image in the repository be used.
//
// It reads the SAME shot plan the video renders from, so it cannot drift from
// what is actually on screen. If an image is not in a shot, it is not in this
// ledger either, and the script exits non-zero.
//
// Run: node --experimental-strip-types scripts/coverage.mjs
import { writeFileSync } from "node:fs";
import { ASSETS, REPO_FILE_COUNT } from "../src/assets.ts";
import { buildShots } from "../src/shots.ts";
import { ACCENT } from "../src/theme.ts";

const { shots, total } = buildShots();
const RUNTIME = 90.0;

const ts = (s) =>
  `${String(Math.floor(s / 60)).padStart(2, "0")}:${(s % 60).toFixed(1).padStart(4, "0")}`;

// Where each image appears.
const placement = new Map(); // slug -> [{ start, kind, segment, reprise }]
for (const s of shots) {
  for (const a of s.assets) {
    if (!placement.has(a.slug)) placement.set(a.slug, []);
    placement.get(a.slug).push({ start: s.start, kind: s.kind, segment: s.segment, reprise: !!s.reprise });
  }
}

const PRODUCTS = [
  ["pm2", "MOTU M2"],
  ["pm4", "MOTU M4"],
  ["pm6", "MOTU M6"],
];

const SEG_NAME = {
  hook: "Hook",
  engine: "The engine",
  m2: "M2",
  m4: "M4",
  m6: "M6",
  close: "Close",
};

const TIER = {
  bleed: "**BLEED** — fills the frame alone, under a camera move",
  panel: "**PANEL** — ultra-wide plan, tracked laterally across the frame",
  split: "**SPLIT** — one half of a diagonal, against a second image",
  mosaic: "**MOSAIC** — a cell in a drifting plane of three or more",
};

const missing = ASSETS.filter((a) => !placement.has(a.slug));
const coveredFiles = ASSETS.reduce((n, a) => n + a.covers.length, 0);
const dupes = ASSETS.filter((a) => a.covers.length > 1);

let md = `# ASSET COVERAGE — MOTU M-Series 90-second vertical reel

Auto-generated by \`scripts/coverage.mjs\` from the same shot plan the video is
rendered from (\`src/shots.ts\`). Nothing in this ledger is hand-maintained, so
it cannot describe a placement the film does not actually contain.

| | |
|---|---|
| **Product image filenames in the repository** | **${REPO_FILE_COUNT}** |
| **Distinct images after content-hash de-duplication** | **${ASSETS.length}** |
| **Distinct images placed in the reel** | **${placement.size}** |
| **Filenames satisfied** | **${coveredFiles} / ${REPO_FILE_COUNT}** |
| **Unused** | **${missing.length}** |
| **Shots in the film** | ${shots.length} |
| **Narration runs** | 00:00.0 – ${ts(total)} |
| **Film runtime** | ${RUNTIME.toFixed(3)} s (the tail is the end screen) |

${missing.length === 0
    ? "✅ **Every M2, M4 and M6 image in the repository appears in the reel.**"
    : `❌ **${missing.length} unused:** ${missing.map((a) => a.slug).join(", ")}`}

---

## Why ${REPO_FILE_COUNT} filenames are ${ASSETS.length} images

The repository's product filenames include ${REPO_FILE_COUNT - ASSETS.length} byte-identical duplicate
pairs — the same photograph filed twice under two different product names. They
are merged here, and the merge is not a nicety: this reel's entire discipline is
that a viewer always knows which of three identical-looking boxes is on screen.
Showing one photograph twice under two different product labels and two
different accent colours would break exactly that.

${dupes.length
    ? dupes
        .map((a) => `- \`${a.covers.join("\`  ==  \`")}\` → used once, as **${a.slug}**`)
        .join("\n")
    : "_(no duplicates found)_"}

---

## Per product

`;

for (const [key, name] of PRODUCTS) {
  const list = ASSETS.filter((a) => a.product === key);
  const placed = list.filter((a) => placement.has(a.slug));
  md += `### ${name}  ·  ${placed.length} / ${list.length} placed  ·  accent \`${ACCENT[key].glow}\`\n\n`;
  md += `| Image | Source filename(s) | Px | Kind | First on screen | How it is staged |\n`;
  md += `|---|---|---|---|---|---|\n`;
  for (const a of list) {
    const ps = (placement.get(a.slug) ?? []).slice().sort((x, y) => x.start - y.start);
    const first = ps[0];
    const where = first
      ? `\`${ts(first.start)}\` · ${SEG_NAME[first.segment]}${ps.length > 1 ? ` _(+${ps.length - 1} more)_` : ""}`
      : "— **UNUSED**";
    md += `| \`${a.slug}\` | ${a.covers.map((c) => `\`${c}\``).join("<br>")} | ${a.w}×${a.h} | ${a.subject} | ${where} | ${first ? TIER[first.kind] : "—"} |\n`;
  }
  md += `\n`;
}

md += `---

## The shot plan, in order

Each shot runs until the next one starts, so the 0.4 s breath between segments
is held by the outgoing picture rather than being a hole in the film.

| In | Out | Hold | Staging | Images | Opening line |
|---|---|---|---|---|---|
`;

for (const s of shots) {
  md += `| \`${ts(s.start)}\` | \`${ts(s.end)}\` | ${(s.end - s.start).toFixed(1)} s | ${s.kind} | ${s.assets
    .map((a) => `\`${a.slug}\``)
    .join(" ")} | ${s.captions[0].t} |\n`;
}

md += `
---

## How the distribution works

**Pinned shots come first.** Seven caption lines have exactly one right
picture — "Two combo inputs", "runs entirely off the USB-C", "Mix knob at the
front", "Four microphone preamps", "A-B switch" and so on. Those are stated
explicitly in \`PINS\` in \`src/shots.ts\` and pulled out of the pool before any
rule runs, because a rule can distribute images fairly but it cannot know that a
sentence about the rear panel needs the rear panel plan.

**Everything left is spread evenly over the shots that are left.** The remainder
is re-divided at every shot rather than once at the start, so the final shot of a
segment is never a dump of whatever was not placed. That is a real failure mode:
the first cut of this plan put seven images into one mosaic at the end of the M6
section.

**The hook and the close draw across all three products**, because those two
sections are *about* all three. Their images are marked as reprises and do not
count towards coverage — every one of them is covered properly inside its own
product's segment, where it is on screen under that product's accent and label.

---

## What is on screen besides the photographs

Full-bleed imagery is only half the frame. The typographic layer over it — held
at 64% opacity throughout, so the picture reads through it — carries:

- the caption lockup, in the two faces from the supplied specimen
- the product tag (M2 / M4 / M6), which is what makes three identical chassis
  distinguishable at a glance
- the input ladder — lit slots counting 2, then 4, then 6
- the engine section's dynamic-range and noise-floor meters and its
  round-trip latency trace
- the spec chips, which deliberately carry facts the narration has no time to say
- the closing comparison ladder, 2 / 4 / 6 side by side

No logo, company name, phone number or website appears anywhere in the body of
the film. All of that is held for the end screen.
`;

writeFileSync("../ASSET_COVERAGE_MSERIES_REEL_90S.md", md);
console.log(
  `ASSET_COVERAGE_MSERIES_REEL_90S.md written — ${placement.size}/${ASSETS.length} distinct images placed, ` +
    `${coveredFiles}/${REPO_FILE_COUNT} filenames satisfied`,
);
if (missing.length) {
  console.error(`UNUSED: ${missing.map((a) => a.slug).join(", ")}`);
  process.exit(1);
}
